### ISSUE TITLE
Iowa改の一番上の装備、16inch三連装砲 Mk.6のリンクがおかしい？

### ISSUE THREAD

**Issue by NaokiSato102** [nekogoro/kcfs#13]
https://akashi-list.me/#w318
になっています。

**Comment by nekogoro** [comment]
No.381 が正しいですね。次回更新で修正します。
https://github.com/nekogoro/kcfs/blob/master/docs/equipments.json#L840

**Comment by nekogoro** [comment]
修正版を反映しました。

**Comment by NaokiSato102** [comment]
修正が確認できたので閉じます
