### ISSUE TITLE
【機能追加】装備種別のアイコン表示

### ISSUE THREAD

**Issue by NaokiSato102** [nekogoro/kcfs#23]
雑な奴でいいんでなんか装備種別のアイコン欲しいです。
現状ではちょっとぱっと見では選ぼうとしてるジャンルで、どの装備ならいい影響が得られる装備のジャンルなのかが分かりにくい。

例）ネルソンに水上機積みたいけど、どれが水上機か、どれならいい効果を得られるかがぱっと見分かりにくい。正答はSwordfish Mk.II改(水偵型) かFairey Seafox改 だが、どれが水上機か、ぱっと見ではわかりにくい。

よろしくお願いいたします。

**Comment by NaokiSato102** [comment]
実物の姿のモチーフだと、水偵、水爆が見分けにくいので、漢字2文字色付きの…的なアイコンでお願いします。良ければ適当に作りますがどうしましょうか。

**Comment by nekogoro** [comment]
承知しました。まずは自分で試作してみます。ご助力をお願いするかもしれませんが、その時はよろしくお願いします。 🙇

**Comment by nekogoro** [comment]
現在のカテゴリと追加すべき装備種別

* 小口径主砲
* 中口径主砲
* 大口径主砲
* 副砲
* 魚雷
    * 魚雷(通常)
    * 甲標的
* 水上機
    * 水偵
    * 水爆
    * 水爆(日本)
* 艦戦
* 艦爆
* 艦攻
* 艦偵
* その他
    * 回転翼機
    * 対空機銃
    * 高射装置
    * ソナー
    * 爆雷
    * 電探
    * 上陸用舟艇
    * 強化弾
    * その他

**Comment by nekogoro** [comment]
ラベル試作(1)
https://codepen.io/nekogoro/pen/GRWZxmx

**Comment by NaokiSato102** [comment]
アンチエイリアスがないからか、文字がつぶれて読みにくいですね。設定ってあるんでしょうかね？
後艦戦の字が色的に更に読みにくいです。
電探は、空/水/両の区別が欲しい気がします。

あと、装備種類アイコンの他に、夜間とか、高角とか、特殊高角とか...
そういう特殊性のあるやつを示す追加アイコンもあるとよさそう。

**Comment by nekogoro** [comment]
フォントは Google fonts の太字フォントを使っているので、ウェイトを細くするなどで見え方も変えられそうです。
あとはフォントに頼らず SVG アイコン化するとかも考えてみます。

**Comment by nekogoro** [comment]
フォントのウェイトを補足し、大まかなカテゴリ＋詳細（艦上機＋夜戦、小口径主砲＋高角砲、など）の組み合わせを試してみました。
https://codepen.io/nekogoro/pen/GRWZxmx

**Comment by nekogoro** [comment]
デザインの変更や調整等はまだまだ余地があるかと思いますが、ひとまずは「装備カテゴリ＋特殊装備」の組み合わせ表示で実装してみます。

**Comment by NaokiSato102** [comment]
いい塩梅だと思います。ただ、アイコンの文字が長ったらしく感じるような気がしました。
小口径主砲 なら、 小主砲 でもいい気がする。

**Comment by nekogoro** [comment]
アイコンの表示と短縮表示を切り替える機能を実装しました。
https://yubari-exp.dev/kcfs/

残課題：

- [ ] url で表示形式の記録を行う

**Comment by NaokiSato102** [comment]
見ました。ええ塩梅です
