### ISSUE TITLE
艦名を検索ボックスで直打ちできるようにしてほしい

### ISSUE THREAD

**Issue by NaokiSato102** [nekogoro/kcfs#3]
誰が何型か覚えきれてないので検索ボックスで直打ちできるようにしてほしい

機能要望はここでいい感じですか？

**Comment by nekogoro** [comment]
@NaokiSato102 ありがとうございます。ご要望に関してもこちらで大丈夫です。

**Comment by nekogoro** [comment]
検索ボックスの追加は前向きに考えてみたいです
サジェスト出したりすれば利便性も上がりそう

**Comment by NaokiSato102** [comment]
サジェストは確かに便利ですね。

あと、入力の際は海外艦はカナでも入れられるようになっていると便利だと思います。アルファベット圏ならまだしも、キリルとか入力が面倒で仕方がありませんから。

**Comment by nekogoro** [comment]
とりあえずベータ版を作ってみました
https://yubari-exp.dev/kcfs/search.html

- [x] 名前直打ちで表示
- [ ] サジェスト
- [ ] カナ・読み仮名対応

**Comment by NaokiSato102** [comment]
試しました。便利でした。  
しかし表示時に同じ漢字が含まれる艦が多く＆改修パターンが多いとかだとサジェストがとっ散らかりすぎる気がするので、未改装、改、改二、それいがいとかの事前フィルタがあった方が良い気がしてきました。  
あとベータ版へのリンクを現行版においてもらった方が皆さん試して意見が上がりやすいと思いました。

**Comment by nekogoro** [comment]
読み仮名・サジェストに対応、現行版にリンクを追加しました。
https://yubari-exp.dev/kcfs/incrementSearch.html

フィルタ機能についても後々実装予定です。

**Comment by nekogoro** [comment]
* オプション案
    * 改装状態によるフィルタ
        * 未改装
        * 改
            * Октябрьская революция, Italia
                * 大鯨と龍鳳、千歳型【水上機母艦】と千歳型【軽空母】、春日丸と大鷹はそれぞれ区別
        * 改派生系
            * 乙改, 丁改
        * 改二
            * Mk.II, due, zwei, два
            * 改母
            * 甲 (千歳型及び日進)
            * Верный, 呂500, UIT-25
        * 改二派生系
            * 改二甲, 改二乙, 改二丙, 改二丁, 改二戊, 改二特
            * Mk.II Mod.2, drei
            * 伊504
* ひらがな・カタカナを区別しない検索

**Comment by NaokiSato102** [comment]
> 読み仮名・サジェストに対応、現行版にリンクを追加しました。
> https://yubari-exp.dev/kcfs/incrementSearch.html
試しました。使いやすかったです。
しかしサジェスト表示がちらちらしてやかましいかもしれません。入力終了まで数秒待ってから表示とした方がいいかもしれません。試作段階なのでそういう細かい調整は後にした方がいいかもしれませんが。
あとはサジェストについて、表記の揺らぎへの対応はどうしましょうか？
現状、Верныйはヴェールヌイでしか検索できませんが、ベールヌイでも検索したいように思えます。揺らぎへの対応はコストが重そうなので必要最低限にするか、別途揺らぎに対応するためのソフトのコードを引用するとか。

**Comment by NaokiSato102** [comment]
可能であればサジェストの際のボタンの色を艦種別に分けたらよさげに思いました。優先度は低めですが。

あと、意見を送る際の迅速さを考慮してβ側にもGitへのリンクがあった方がいい気がしてきました。

**Comment by nekogoro** [comment]
> ちらつき

フッターをなくせばある程度は軽減しそうとは考えていましたが、表示を遅延させるのもありですね。

> ゆらぎへの対応

1隻に対して検索可能な語句を複数用意する（潜水艦は正式名称と愛称の双方で検索したい）でも対応できそうですが、データ数が多そうな場合は外部ライブラリ導入も考えます。

> ボタンの色
> Git へのリンク

検討します。

**Comment by nekogoro** [comment]
ちらつき防止、艦種別色変更、改以上のフィルタ、gitへのリンクを追加しました。

揺らぎ対応、新しいフィルタの追加も対応予定です。

**Comment by NaokiSato102** [comment]
試験実装版の使用も結構うまくいっているのでとりあえず現行版への統合してはいかがでしょうか？もしくは統合してみたのを新たに試験版とするか。
統合してみないとわからない問題点もあるかもですので。

後そろそろこのissueは閉じて残った項目は独立させたい気がしますね。

追伸
このissueのcloseも私もできるようになってるみたいです。詳しくは知らないんですが、たぶんデフォルト値の変更とかで対応しないとダメなのかも？

**Comment by nekogoro** [comment]
> 現行版への統合

現行版への統合、もしくはレポジトリを分けて開発することを検討しています。

> issueのclose

Organization では権限を変えられるようですが、個人のレポジトリでそれが可能かどうか（調べ中ではあるものの）まだわかっていません。いざとなったら再オープンも可能なのでなんとかなると思います。

**Comment by nekogoro** [comment]
現行版ページにインクリメンタルサーチを統合しました。
統合後に発見された問題については別途 Issue を立てて対応しようと思います。
