### ISSUE TITLE
3/27の艦これの更新に対応

### ISSUE THREAD

**Issue by NaokiSato102** [nekogoro/kcfs#7]
明記補正が艦これの更新により変更されたのでこれに対応願います。

以下メンテのアナウンスより

> 06▼【探照灯】系装備の能力上方微修正
【探照灯】系装備の能力が上方微修正され、「比叡」「霧島」「神通」などの艦の交戦能力をより向上することが可能になります。
>
>07▼水上艦要員【熟練見張員】の能力上方修正/運用性拡張
水上艦要員【熟練見張員】の能力が上方修正され、主に日本水雷戦隊の構成艦の戦闘能力をより高めることが可能となります。
また、【熟練見張員】の補強増設装備スロットでの運用も可能となります。
>
>14▼【日本重巡洋艦】各艦の能力上方微修正
【日本重巡洋艦】古鷹型・青葉型・妙高型・高雄型・最上型・利根型各艦の能力が上方微修正され、
「20.3cm(2号)連装砲」「20.3cm(3号)連装砲」の運用で、その交戦能力をより高めることが可能です。
>
>15▼【日本重巡洋艦】能力上方微修正の補足
特に【20.3cm(3号)連装砲】を妙高型・高雄型で運用、最上型・利根型で集中運用することで従来より高い能力を発揮します。
「水上電探」系装備と組み合わせて案用することで、さらに高い交戦能力を発揮するこも可能になります。
>
>16▼軽空母【鳳翔】【大鷹】【神鷹】の能力上方微修正
軽空母【鳳翔】及び護衛空母【大鷹(含む春日丸)】【神鷹】と「九六式艦戦改」及び「九六式艦戦」の運用適正が上方微修正され、搭載運用時の交戦能力が従来より若干ですが向上します。

**Comment by nekogoro** [comment]
対応しました
https://github.com/nekogoro/kcfs/releases/tag/1.0.20200329

**Comment by NaokiSato102** [comment]
対応完了お疲れさまでした。このissueはcloseとしましょう。
あと現状他所の人にもcloseできるようになっているので権限を絞るべきかと思います。

**Comment by nekogoro** [comment]
ありがとうございます。設定してみます。
